circle: deps: install automake and libtool because building secp256k1 needs them
background: https://app.circleci.com/pipelines/github/snarfed/bridgy-fed/3673/workflows/5883377b-99e9-4e33-baa6-be151bab2d9b/jobs/4020

```
  Building wheel for secp256k1 (setup.py) ... [?25l- \ | error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [79 lines of output]
      0.29.2
      /home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      /home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      Using bundled libsecp256k1
      /home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are deprecated.
      !!

              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:

              License :: OSI Approved :: MIT License

              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************

      !!
        self._finalize_license_expression()
      running bdist_wheel
      The [wheel] section is deprecated. Use [bdist_wheel] instead.
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-312/secp256k1
      copying secp256k1/__init__.py -> build/lib.linux-x86_64-cpython-312/secp256k1
      copying secp256k1/__main__.py -> build/lib.linux-x86_64-cpython-312/secp256k1
      running build_clib
      Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 274.
      autoreconf: error: aclocal failed with exit status: 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 35, in <module>
        File "/tmp/pip-install-2kz3nxcd/secp256k1_d82ba4a949224880b9d2aeaa204eab35/setup.py", line 267, in <module>
          setup(
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 186, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 202, in run_commands
          dist.run_commands()
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1002, in run_commands
          self.run_command(cmd)
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/dist.py", line 1104, in run_command
          super().run_command(command)
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-2kz3nxcd/secp256k1_d82ba4a949224880b9d2aeaa204eab35/setup.py", line 112, in run
          _bdist_wheel.run(self)
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py", line 370, in run
          self.run_command("build")
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 357, in run_command
          self.distribution.run_command(command)
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/dist.py", line 1104, in run_command
          super().run_command(command)
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
          cmd_obj.run()
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 357, in run_command
          self.distribution.run_command(command)
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/dist.py", line 1104, in run_command
          super().run_command(command)
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 1021, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-2kz3nxcd/secp256k1_d82ba4a949224880b9d2aeaa204eab35/setup.py", line 168, in run
          subprocess.check_call(
        File "/home/circleci/.pyenv/versions/3.12.10/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/tmp/pip-install-2kz3nxcd/secp256k1_d82ba4a949224880b9d2aeaa204eab35/libsecp256k1/autogen.sh']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for secp256k1
[?25h  Running setup.py clean for secp256k1
```

related:
https://github.com/rustyrussell/secp256k1-py/issues/24
https://github.com/buffer/pylibemu/issues/24